require: rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - node_modules/**/*
    - test/dummy/db/schema.rb

Layout/IndentationConsistency:
  Exclude:
    - lib/generators/loco/file_injector/templates/connection.rb

Layout/InitialIndentation:
  Exclude:
    - lib/generators/loco/file_injector/templates/application_controller.rb
    - lib/generators/loco/file_injector/templates/connection.rb

Layout/TrailingEmptyLines:
  Exclude:
    - lib/generators/loco/file_injector/templates/application_controller.rb

Metrics/BlockLength:
  Exclude:
    - loco-rails.gemspec
    - test/dummy/config/routes.rb
    - test/loco/*

Metrics/ClassLength:
  Exclude:
    - test/integration/**/*
    - test/loco/**/*

Metrics/MethodLength:
  Max: 12

Metrics/ParameterLists:
  Exclude:
    - lib/loco-rails.rb

Naming/FileName:
  Exclude:
    - lib/loco-rails.rb

Rails:
  Enabled: true

Rails/ApplicationJob:
  Exclude:
    - app/jobs/loco/*

Rails/ActionControllerFlashBeforeRender:
  Exclude:
    - test/dummy/app/controllers/admin/sessions_controller.rb

Rails/I18nLocaleTexts:
  Enabled: false

Style/ArgumentsForwarding:
  Exclude:
    - lib/loco/ws_connection_finder.rb

Style/ArrayCoercion:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - lib/generators/loco/file_injector/templates/application_controller.rb
    - lib/generators/loco/file_injector/templates/connection.rb

Style/LambdaCall:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - lib/generators/loco/file_injector/templates/application_controller.rb
