AllCops:
  TargetRubyVersion: 2.4

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: rails
  Exclude:
    - lib/generators/loco/file_injector/templates/connection.rb

Layout/InitialIndentation:
  Enabled: true
  Exclude:
    - lib/generators/loco/file_injector/templates/application_controller.rb
    - lib/generators/loco/file_injector/templates/connection.rb

Layout/TrailingBlankLines:
  Enabled: true
  Exclude:
    - lib/generators/loco/file_injector/templates/application_controller.rb

Rails:
  Enabled: true

Rails/ApplicationJob:
  Enabled: true
  Exclude:
    - app/jobs/loco/*

Rails/ApplicationRecord:
  Enabled: true
  Exclude:
    - app/models/loco/notification.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - lib/generators/loco/file_injector/templates/application_controller.rb
    - lib/generators/loco/file_injector/templates/connection.rb

Style/MethodDefParentheses:
  Enabled: false

Style/MixinUsage:
  Enabled: true
  Exclude:
    - lib/generators/loco/file_injector/templates/application_controller.rb