require: rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - node_modules/**/*
    - test/dummy/db/schema.rb

Layout/IndentationConsistency:
  Enabled: true
  Exclude:
    - lib/generators/loco/file_injector/templates/connection.rb

Layout/InitialIndentation:
  Enabled: true
  Exclude:
    - lib/generators/loco/file_injector/templates/application_controller.rb
    - lib/generators/loco/file_injector/templates/connection.rb

Layout/LineLength:
  Enabled: true
  Max: 103
  Exclude:
    - test/dummy/config/environments/production.rb

Layout/TrailingEmptyLines:
  Enabled: true
  Exclude:
    - lib/generators/loco/file_injector/templates/application_controller.rb

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - loco-rails.gemspec
    - test/dummy/config/routes.rb
    - test/loco/*

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - test/integration/**/*
    - test/loco/**/*

Metrics/MethodLength:
  Enabled: true
  Max: 12

Naming/FileName:
  Enabled: true
  Exclude:
    - lib/loco-rails.rb

Rails:
  Enabled: true

Rails/ApplicationJob:
  Enabled: true
  Exclude:
    - app/jobs/loco/*

Style/ArrayCoercion:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - lib/generators/loco/file_injector/templates/application_controller.rb
    - lib/generators/loco/file_injector/templates/connection.rb

Style/LambdaCall:
  Enabled: false

Style/MixinUsage:
  Enabled: true
  Exclude:
    - lib/generators/loco/file_injector/templates/application_controller.rb
