AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - node_modules/**/*
    - test/**/*

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods
  Exclude:
    - lib/generators/loco/file_injector/templates/connection.rb

Layout/InitialIndentation:
  Enabled: true
  Exclude:
    - lib/generators/loco/file_injector/templates/application_controller.rb
    - lib/generators/loco/file_injector/templates/connection.rb

Layout/TrailingBlankLines:
  Enabled: true
  Exclude:
    - lib/generators/loco/file_injector/templates/application_controller.rb

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - loco-rails.gemspec
    - test/dummy/db/schema.rb

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - test/dummy/app/controllers/admin/articles_controller.rb

Metrics/LineLength:
  Enabled: true
  Exclude:
    - test/dummy/db/schema.rb

Naming/FileName:
  Enabled: true
  Exclude:
    - lib/loco-rails.rb

Rails:
  Enabled: true

Rails/ApplicationJob:
  Enabled: true
  Exclude:
    - app/jobs/loco/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - lib/generators/loco/file_injector/templates/application_controller.rb
    - lib/generators/loco/file_injector/templates/connection.rb

Style/MethodDefParentheses:
  Enabled: false

Style/MixinUsage:
  Enabled: true
  Exclude:
    - lib/generators/loco/file_injector/templates/application_controller.rb