require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - node_modules/**/*
    - test/dummy/db/schema.rb

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods
  Exclude:
    - lib/generators/loco/file_injector/templates/connection.rb

Layout/InitialIndentation:
  Enabled: true
  Exclude:
    - lib/generators/loco/file_injector/templates/application_controller.rb
    - lib/generators/loco/file_injector/templates/connection.rb

Layout/LineLength:
  Enabled: true
  Max: 97
  Exclude:
    - test/dummy/config/environments/production.rb

Layout/TrailingEmptyLines:
  Enabled: true
  Exclude:
    - lib/generators/loco/file_injector/templates/application_controller.rb

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - loco-rails.gemspec
    - test/dummy/config/routes.rb

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - test/integration/**/*

Metrics/MethodLength:
  Enabled: true
  Max: 12
  Exclude:
    - test/dummy/app/controllers/admin/articles_controller.rb

Naming/FileName:
  Enabled: true
  Exclude:
    - lib/loco-rails.rb

Rails:
  Enabled: true

Rails/ApplicationJob:
  Enabled: true
  Exclude:
    - app/jobs/loco/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - lib/generators/loco/file_injector/templates/application_controller.rb
    - lib/generators/loco/file_injector/templates/connection.rb

Style/MixinUsage:
  Enabled: true
  Exclude:
    - lib/generators/loco/file_injector/templates/application_controller.rb