version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - "3306"
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis:5.0.5
    expose:
      - "6379"
    ports:
      - "6380:6379"
    volumes:
      - 'redis:/var/lib/redis/data'

volumes:
  mysql:
  redis:
