version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql:
