window.App =
  Loco: null
  IdentityMap: null
  Wire: null
  Env:
    loco: null
    namespaceController: null
    controller: null
    action: null
    scope: null
  Mix: null
  Mixins: {}
  UI: {}
  Controllers: {}
  Models: {}
  Views: {}
  Services: {}
  Helpers: {}
  Presenters: {}
  Validators: {}
  I18n: {}
  Utils: {}